### ISSUE TITLE
Test don't compile in copr

### ISSUE THREAD

**Issue by remilauzier** [plotters-rs/plotters-svg#4]
https://download.copr.fedorainfracloud.org/results/remilauzier/plotters/fedora-rawhide-x86_64/02251721-rust-plotters-svg/builder-live.log.gz

You can see at the end that the failed failed to compiled.

**Comment by remilauzier** [comment]
https://kojipkgs.fedoraproject.org//work/tasks/9218/71009218/build.log

error[E0433]: failed to resolve: use of undeclared crate or module `plotters`
   --> src/svg.rs:581:9
    |
581 |     use plotters::prelude::*;
    |         ^^^^^^^^ use of undeclared crate or module `plotters`
error[E0433]: failed to resolve: use of undeclared crate or module `plotters`
   --> src/svg.rs:580:9
    |
580 |     use plotters::element::Circle;
    |         ^^^^^^^^ use of undeclared crate or module `plotters`
error[E0433]: failed to resolve: use of undeclared crate or module `plotters`
   --> src/svg.rs:582:9
    |
582 |     use plotters::style::text_anchor::{HPos, Pos, VPos};
    |         ^^^^^^^^ use of undeclared crate or module `plotters`
error[E0432]: unresolved imports `plotters::element::Circle`, `plotters::style::text_anchor::HPos`, `plotters::style::text_anchor::Pos`, `plotters::style::text_anchor::VPos`

**Comment by 38** [comment]
Hi, thanks for reporting this issue. This should be fixed in the master branch, as well as the latest published version 0.3.1

Please let me know if this fixes your issue.

Thanks for the help!

**Comment by remilauzier** [comment]
Everything work! https://koji.fedoraproject.org/koji/taskinfo?taskID=71091879
